services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.52.0
    command: >
      npx -y playwright@1.52.0 run-server --port 3000 --host 0.0.0.0
    ports:
      - "3000:3000"  # Playwright server port
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/home/pwuser/.Xauthority:ro
      - .:/app:rw
    network_mode: bridge
    user: pwuser
    working_dir: /home/pwuser
    init: true
    ipc: host
    security_opt:
      - seccomp:unconfined
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
